from itertools import chain
import cm2py as cm2
import numpy as np
import colorsys
from pyperclip import copy as cpy_cb

rainbow_arr = []

def rainbowgen(num_colors=2048):
    rainbow = []
    hues = np.linspace(0, 1, num_colors)

    for hue in hues:
        r, g, b = colorsys.hsv_to_rgb(hue, 1, 1)
        rainbow.append((int(r * 255), int(g * 255), int(b * 255)))
    
    return rainbow

rainbow_arr = rainbowgen().copy()

save = cm2.Save()

blocks = []

wmblocks = []

connections = []

wm = 'Generated by ZachTheArcticFox :3'

px = 0
wmx = len(wm)

asciiwm = []

for i in wm:
    asciiwm.append(ord(i))

for i in range(len(wm)):
    wmblocks.append(save.addBlock(cm2.TEXT, (wmx,0,0), False, [asciiwm[i]]))
    wmx += 1

for i in range(len(rainbow_arr)):
    j = [t for t in rainbow_arr[i]]
    j.append(2)
    blocks.append(save.addBlock(cm2.TILE, (px, px, px), not i, j, False))
    px += 0.1

saveString = save.exportSave()
cpy_cb(saveString)